version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: m2p
    main: ./cmd/m2p
    binary: m2p
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: m2p
    builds: [m2p]
    name_template: "m2p_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^refactor:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: ralvarez
    name: m2p
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
